--  NOTE: This is a test
--  TODO: This is a test
--  HACK: This is a test
--  WARN: This is a test
--  PERF: This is a test
--  TEST: This is a test
--  ERROR This is a test

-- FIX: Fix this ASAP
--
-- this is a { test }
-- "This is another test"
